#!/bin/bash
#Author spawN
#spawn@namek.fr
#Creation 21.01.18

#Gathering Network informations about your installation


#First : Make sure only root can run this script

if [ $EUID -ne 0 ]; then
        echo "This script must be run as root!"
        exit 126
fi
## Then we check on which distro we are ! 

if [ $release = Debian ] || [$release = Fedora ];
	then echo "c'est une $release"
fi
#Second : The Variables

ippub=`curl -s ifconfig.ovh`
eth4=`ip -o -4 a | awk '{print $2}' | tr -d lo  | sed /^$/d | while read eth; do ip -o -4 a show $eth;done | awk '{print $2,$4}' | sort -u`
eth6=`ip -o -6 a | awk '{print $2}' | tr -d lo  | sed /^$/d | while read eth; do ip -o -6 a show $eth;done | awk '{print $2,$4}' | sort -u`
netadp=`ip -o -4 a | awk '{print $2}' | tr -d lo  | sed /^$/d | sort -u`
release=`lsb_release -i | awk '{print $3}'`

#Check if ethtool is installed

cethtool=`dpkg -l | grep 'ethtool' | grep ii`

#Third : Scipt Beginning

timeout 2s echo -e "Public IP: $ippub"
echo -e "IP on $eth4"
echo -e "IP on $eth6"

echo -e "\nGathering the NIC(s) informations.."
echo ""
echo $netadp
if [ -z "$cethtool" ]
then
	echo -e "\npackage 'ethtool' is not installed, please intall it to continue" 
	exit 1
else
	true
fi

for nic in $netadp
	do
		ethtool $nic | egrep -i 'speed|detected'
		ethtool -S $nic | grep errors
	done


while read -s -r -n 1 -p 'Ping : EU (1) / CA (2) / SBG (3) / Google (4) / Quit (5):' todo;
	do
	case $todo in
		1) echo -e "\nTesting on RBX :"
			ping -c 5 rbx.proof.ovh.net 
			mtr -c1 -r rbx.proof.ovh.net
			continue
		;;
		2) echo -e "\nTesting on CA : "
			ping -c 5 bhs.proof.ovh.net
			mtr -c1 -r bhs.proof.ovh.net
			continue
		;;
		3) echo -e "\nTesting on SBG :"
			ping -c 5 sbg.proof.ovh.net
			mtr -c1 -r sbg.proof.ovh.net
			continue
		;;
		4) echo -e "\nTesting on Google :"
			ping -c 5 8.8.8.8
			mtr -c1 -r 8.8.8.8
			continue
		;;
		5) echo -e "\nLeaving Pings Tests."
			break
		;;
		*) echo -e "\nWrong Key!"
			continue
		;;
	esac
done
